/// UI strings in Arabic (default) and English. Kept as a simple map so non-developers on the
/// team can edit wording quickly. Usage: `S.of(context).t('today')`.
library;

import 'package:flutter/widgets.dart';

import '../state/app_state.dart';

const Map<String, Map<String, String>> _strings = {
  'app_name': {'ar': 'خطوة حياة', 'en': 'LifeStep'},
  'tagline': {
    'ar': 'خطوات يومية صغيرة لضغط وسكر أفضل',
    'en': 'Small daily steps for better blood pressure and blood sugar',
  },
  'disclaimer': {
    'ar':
        'هذا التطبيق يدعم خطة طبيبك ولا يحل محلها. لا تغيّر أدويتك دون استشارة طبيبك.',
    'en':
        "This app supports your doctor's plan, it does not replace it. Don't change your medicines without your doctor.",
  },
  'choose_language': {'ar': 'اختر اللغة', 'en': 'Choose language'},
  'start_new': {'ar': 'ابدأ خطتي', 'en': 'Start my plan'},
  'try_demo': {'ar': 'جرّب المريض التجريبي', 'en': 'Try the demo patient'},
  'next': {'ar': 'التالي', 'en': 'Next'},
  'back': {'ar': 'رجوع', 'en': 'Back'},
  'skip': {'ar': 'تخطٍّ', 'en': 'Skip'},
  'done': {'ar': 'تم', 'en': 'Done'},
  'save': {'ar': 'حفظ', 'en': 'Save'},
  'close': {'ar': 'إغلاق', 'en': 'Close'},
  'retry': {'ar': 'إعادة المحاولة', 'en': 'Try again'},
  'error_generic': {
    'ar': 'حدث خطأ. تأكد من تشغيل الخادم.',
    'en': 'Something went wrong. Is the server running?',
  },
  // Onboarding
  'q_condition': {'ar': 'ما هي حالتك؟', 'en': 'What is your condition?'},
  'coming_soon': {'ar': 'قريبًا', 'en': 'Coming soon'},
  'q_name': {'ar': 'ما اسمك؟ (اختياري)', 'en': 'Your name (optional)'},
  'q_age_sex': {'ar': 'عمرك وجنسك', 'en': 'Your age and sex'},
  'age': {'ar': 'العمر', 'en': 'Age'},
  'years': {'ar': 'سنة', 'en': 'years'},
  'male': {'ar': 'ذكر', 'en': 'Male'},
  'female': {'ar': 'أنثى', 'en': 'Female'},
  'q_body': {'ar': 'وزنك وطولك', 'en': 'Your weight and height'},
  'weight': {'ar': 'الوزن', 'en': 'Weight'},
  'height': {'ar': 'الطول', 'en': 'Height'},
  'kg': {'ar': 'كجم', 'en': 'kg'},
  'cm': {'ar': 'سم', 'en': 'cm'},
  'q_meds': {
    'ar': 'ما الأدوية التي تأخذها للضغط؟',
    'en': 'Which blood pressure medicines do you take?',
  },
  'meds_hint': {'ar': 'اختر كل ما ينطبق', 'en': 'Choose all that apply'},
  'other_med': {
    'ar': 'دواء آخر (اكتب الاسم)',
    'en': 'Other medicine (type name)',
  },
  'none': {'ar': 'لا شيء', 'en': 'None'},
  'q_limits': {
    'ar': 'هل لديك أي صعوبة في الحركة؟',
    'en': 'Any difficulty moving?',
  },
  'q_activity': {'ar': 'كم تتحرك عادةً؟', 'en': 'How active are you usually?'},
  'q_diet': {
    'ar': 'ما الذي ينطبق على أكلك؟',
    'en': 'What fits your eating habits?',
  },
  'generating': {
    'ar': 'نُعدّ خطتك الشخصية…',
    'en': 'Building your personal plan…',
  },
  'generating_sub': {
    'ar': 'نختار توصيات من الإرشادات الطبية ونكيّفها لك',
    'en': 'Picking guideline recommendations and adapting them to you',
  },
  // Home
  'tab_today': {'ar': 'خطتي', 'en': 'My plan'},
  'tab_bp': {'ar': 'الضغط', 'en': 'Pressure'},
  'tab_meal': {'ar': 'وجبتي', 'en': 'My meal'},
  'tab_report': {'ar': 'التقرير', 'en': 'Report'},
  'hello': {'ar': 'مرحبًا', 'en': 'Hello'},
  'today': {'ar': 'اليوم', 'en': 'Today'},
  'this_week': {'ar': 'هذا الأسبوع', 'en': 'This week'},
  'this_month': {'ar': 'هذا الشهر', 'en': 'This month'},
  'progress': {'ar': 'أنجزت {done} من {total}', 'en': '{done} of {total} done'},
  'why_matters': {'ar': 'لماذا هذا مهم؟', 'en': 'Why this matters'},
  'made_for_you': {'ar': 'مُكيّف لك', 'en': 'Made for you'},
  'source': {'ar': 'المصدر', 'en': 'Source'},
  'feel_unwell': {'ar': 'أشعر بتعب', 'en': 'I feel unwell'},
  'demo_ai': {
    'ar': 'وضع العرض (بدون ذكاء اصطناعي)',
    'en': 'Demo mode (offline AI)',
  },
  'ai_by': {'ar': 'أُعدّت بواسطة Claude', 'en': 'Generated by Claude'},
  'all_done': {
    'ar': 'أحسنت! أنجزت كل أهداف اليوم',
    'en': 'Well done! All of today\'s goals are done',
  },
  // Adapt
  'adapt_title': {'ar': 'لاحظنا شيئًا', 'en': 'We noticed something'},
  'adapt_q': {
    'ar': 'لم تُنجز «{goal}» منذ {days} أيام. ما السبب؟',
    'en': 'You haven\'t done "{goal}" for {days} days. What got in the way?',
  },
  'r_too_hard': {'ar': 'صعب عليّ', 'en': 'Too hard'},
  'r_no_time': {'ar': 'ليس لدي وقت', 'en': 'No time'},
  'r_pain': {'ar': 'يسبب لي ألمًا', 'en': 'It causes pain'},
  'r_forgot': {'ar': 'أنسى', 'en': 'I forget'},
  'r_dont_like': {'ar': 'لا أحبه', 'en': "I don't like it"},
  'r_keep': {'ar': 'سأحاول مرة أخرى', 'en': "I'll try again"},
  'adapt_new': {'ar': 'هدفك الجديد', 'en': 'Your new goal'},
  'adapt_ok': {'ar': 'حسنًا، فهمت', 'en': 'OK, got it'},
  // BP
  'log_bp': {'ar': 'سجّل قراءة الضغط', 'en': 'Log a reading'},
  'systolic': {'ar': 'الانقباضي (الرقم الأعلى)', 'en': 'Systolic (top number)'},
  'diastolic': {
    'ar': 'الانبساطي (الرقم الأسفل)',
    'en': 'Diastolic (bottom number)',
  },
  'pulse': {'ar': 'النبض', 'en': 'Pulse'},
  'any_symptoms': {
    'ar': 'هل تشعر بأي من هذه الآن؟',
    'en': 'Do you feel any of these now?',
  },
  'save_reading': {'ar': 'حفظ القراءة', 'en': 'Save reading'},
  'saved': {'ar': 'تم الحفظ', 'en': 'Saved'},
  'trend': {'ar': 'آخر 4 أسابيع', 'en': 'Last 4 weeks'},
  'recent': {'ar': 'آخر القراءات', 'en': 'Recent readings'},
  'no_readings': {'ar': 'لا توجد قراءات بعد', 'en': 'No readings yet'},
  'measure_tip': {
    'ar':
        'اجلس 5 دقائق، ظهرك مسنود وقدماك على الأرض، وذراعك على الطاولة بمستوى القلب.',
    'en':
        'Sit for 5 minutes, back supported, feet flat, arm on a table at heart level.',
  },
  // Symptoms
  'symptom_title': {'ar': 'كيف تشعر؟', 'en': 'How do you feel?'},
  'symptom_sub': {
    'ar': 'اختر ما تشعر به الآن',
    'en': 'Choose what you feel right now',
  },
  'check_now': {'ar': 'تحقّق', 'en': 'Check'},
  'no_warning': {
    'ar':
        'لا توجد علامات خطر مما اخترت. إذا ساءت حالتك أو قلقت، اتصل بطبيبك أو 997.',
    'en':
        'None of the warning signs selected. If you get worse or are worried, call your doctor or 997.',
  },
  'chest_pain': {'ar': 'ألم في الصدر', 'en': 'Chest pain'},
  'severe_headache': {'ar': 'صداع شديد', 'en': 'Severe headache'},
  'shortness_of_breath': {'ar': 'ضيق في التنفس', 'en': 'Shortness of breath'},
  'vision_changes': {'ar': 'تغيّر في النظر', 'en': 'Vision changes'},
  'weakness_numbness': {'ar': 'ضعف أو تنميل', 'en': 'Weakness or numbness'},
  'confusion_speech': {
    'ar': 'تشوّش أو صعوبة في الكلام',
    'en': 'Confusion or trouble speaking',
  },
  // Emergency
  'call_997': {'ar': 'اتصل بالإسعاف 997', 'en': 'Call ambulance 997'},
  'im_safe': {'ar': 'أنا بخير الآن', 'en': "I'm safe now"},
  'emergency_note': {
    'ar': 'هذا تنبيه آلي ثابت وليس تشخيصًا.',
    'en': 'This is a fixed automatic alert, not a diagnosis.',
  },
  // Meal
  'meal_title': {'ar': 'هل وجبتي مالحة؟', 'en': 'Is my meal salty?'},
  'meal_sub': {
    'ar': 'صوّر وجبتك وسنقدّر كمية الملح ونقترح بديلًا بسيطًا',
    'en':
        "Take a photo of your meal and we'll estimate the salt and suggest a simple swap",
  },
  'take_photo': {'ar': 'التقط صورة', 'en': 'Take a photo'},
  'choose_photo': {'ar': 'اختر صورة', 'en': 'Choose a photo'},
  'analyzing': {'ar': 'جارٍ التحليل…', 'en': 'Analysing…'},
  'salt_low': {'ar': 'ملح قليل غالبًا', 'en': 'Likely low in salt'},
  'salt_medium': {'ar': 'ملح متوسط غالبًا', 'en': 'Likely medium salt'},
  'salt_high': {'ar': 'ملح عالٍ غالبًا', 'en': 'Likely high in salt'},
  'salt_unknown': {'ar': 'غير معروف', 'en': 'Unknown'},
  'try_instead': {'ar': 'جرّب بدلًا من ذلك', 'en': 'Try instead'},
  'estimate_note': {
    'ar': 'تقدير من الصورة فقط، وليس قياسًا دقيقًا.',
    'en': 'A rough estimate from a photo, not a measurement.',
  },
  // Report
  'report_title': {
    'ar': 'تقرير الشهر لطبيبك',
    'en': 'Monthly report for your doctor',
  },
  'adherence': {'ar': 'التزامك بالخطة', 'en': 'Plan adherence'},
  'avg_bp': {'ar': 'متوسط الضغط', 'en': 'Average BP'},
  'bp_change': {'ar': 'تغيّر الضغط', 'en': 'BP change'},
  'readings_count': {'ar': 'عدد القراءات', 'en': 'Readings'},
  'difficulties': {
    'ar': 'الصعوبات التي واجهتك',
    'en': 'Difficulties you reported',
  },
  'hardest_goals': {'ar': 'الأهداف الأصعب', 'en': 'Hardest goals'},
  'open_pdf': {'ar': 'افتح التقرير PDF', 'en': 'Open PDF report'},
  'pdf_note': {
    'ar': 'التقرير بالإنجليزية ليسهل على الطبيب قراءته.',
    'en': 'The PDF is in English for your doctor.',
  },
  // Redesign additions
  'cat_diet': {'ar': 'الأكل', 'en': 'Food'},
  'cat_activity': {'ar': 'الحركة', 'en': 'Movement'},
  'cat_medication': {'ar': 'الدواء', 'en': 'Medicine'},
  'cat_monitoring': {'ar': 'القياس', 'en': 'Check-up'},
  'cat_weight': {'ar': 'الوزن', 'en': 'Weight'},
  'cat_lifestyle': {'ar': 'نمط الحياة', 'en': 'Lifestyle'},
  'plan_today': {'ar': 'خطة اليوم', 'en': "Today's plan"},
  'plan_week': {'ar': 'خطة الأسبوع', 'en': "This week's plan"},
  'plan_month': {'ar': 'خطة الشهر', 'en': "This month's plan"},
  'cheer_start': {
    'ar': 'لنبدأ بخطوة صغيرة',
    'en': "Let's start with one small step",
  },
  'cheer_mid': {'ar': 'أحسنت، استمر!', 'en': 'Good going, keep it up!'},
  'cheer_almost': {'ar': 'بقي القليل!', 'en': 'Almost there!'},
  'cheer_done': {'ar': 'رائع! أنجزت كل شيء', 'en': 'Wonderful! All done'},
  'tap_to_tick': {
    'ar': 'اضغط على الهدف عند إنجازه',
    'en': 'Tap a goal when you have done it',
  },
  'why_short': {'ar': 'لماذا؟', 'en': 'Why?'},
  'done_label': {'ar': 'تم', 'en': 'Done'},
  'last_reading': {'ar': 'آخر قراءة', 'en': 'Last reading'},
  'new_reading': {'ar': 'قراءة جديدة', 'en': 'New reading'},
  'top_number': {'ar': 'الرقم الأعلى', 'en': 'Top number'},
  'bottom_number': {'ar': 'الرقم الأسفل', 'en': 'Bottom number'},
  'bp_in_target': {'ar': 'ضمن المستهدف', 'en': 'In target range'},
  'bp_above': {'ar': 'أعلى من المستهدف', 'en': 'Above target'},
  'bp_crisis': {'ar': 'مرتفع جدًا — خطر', 'en': 'Very high — danger'},
  'have_symptoms': {'ar': 'أشعر بأعراض الآن', 'en': 'I have symptoms now'},
  'how_to_measure': {
    'ar': 'كيف أقيس بشكل صحيح؟',
    'en': 'How to measure correctly',
  },
  'mmhg': {'ar': 'ملم زئبق', 'en': 'mmHg'},
  'meal_step1': {'ar': 'صوّر طبقك', 'en': 'Photograph your plate'},
  'meal_step2': {'ar': 'نقدّر كمية الملح', 'en': 'We estimate the salt'},
  'meal_step3': {'ar': 'نقترح بديلًا بسيطًا', 'en': 'We suggest a simple swap'},
  'another_photo': {'ar': 'صورة أخرى', 'en': 'Another photo'},
  'down_by': {'ar': 'انخفض {n}', 'en': 'Down {n}'},
  'up_by': {'ar': 'ارتفع {n}', 'en': 'Up {n}'},
  'start': {'ar': 'البداية', 'en': 'Start'},
  'end': {'ar': 'الآن', 'en': 'Now'},
  'welcome_title': {'ar': 'مرحبًا بك في خطوة حياة', 'en': 'Welcome to LifeStep'},
  // History intake (asked before the plan)
  'doc_hello': {
    'ar':
        'أهلًا بك! أنا مساعدتك الصحية. سأسألك بعض الأسئلة عن صحتك أولًا، ثم أبني لك نمط حياة يناسبك.',
    'en':
        "Hello! I'm your health guide. I'll ask a few questions about your health first, then build a lifestyle that fits you.",
  },
  'q_diagnosed': {
    'ar': 'متى عرفت أن لديك ارتفاع ضغط؟',
    'en': 'When were you told you have high blood pressure?',
  },
  'd_this_year': {'ar': 'هذه السنة', 'en': 'This year'},
  'd_1_5_years': {'ar': 'من سنة إلى 5 سنوات', 'en': '1 to 5 years ago'},
  'd_over_5_years': {'ar': 'أكثر من 5 سنوات', 'en': 'More than 5 years ago'},
  'd_unknown': {'ar': 'لا أتذكر', 'en': "I don't remember"},
  'q_usual_bp': {
    'ar': 'كم يكون ضغطك عادةً؟',
    'en': 'What is your blood pressure usually?',
  },
  'usual_bp_hint': {
    'ar': 'تقريبًا، من جهاز البيت أو آخر زيارة',
    'en': 'Roughly, from your home monitor or last visit',
  },
  'dont_know': {'ar': 'لا أعرف', 'en': "I don't know"},
  'q_conditions': {
    'ar': 'هل لديك أمراض أخرى؟',
    'en': 'Do you have any other conditions?',
  },
  'c_diabetes': {'ar': 'السكري', 'en': 'Diabetes'},
  'c_high_cholesterol': {'ar': 'ارتفاع الكوليسترول', 'en': 'High cholesterol'},
  'c_heart_disease': {'ar': 'مرض في القلب', 'en': 'Heart disease'},
  'c_stroke': {'ar': 'جلطة دماغية سابقة', 'en': 'Previous stroke'},
  'c_kidney_disease': {'ar': 'مرض في الكلى', 'en': 'Kidney disease'},
  'q_family': {
    'ar': 'هل أصيب أحد والديك أو إخوتك بمرض قلب أو جلطة؟',
    'en': 'Has a parent, brother or sister had heart disease or a stroke?',
  },
  'yes': {'ar': 'نعم', 'en': 'Yes'},
  'no': {'ar': 'لا', 'en': 'No'},
  'not_sure': {'ar': 'لست متأكدًا', 'en': 'Not sure'},
  'q_smoking': {'ar': 'هل تدخن؟', 'en': 'Do you smoke?'},
  's_no': {'ar': 'لا أدخن', 'en': "I don't smoke"},
  's_cigarettes': {'ar': 'أدخن السجائر', 'en': 'Cigarettes'},
  's_shisha': {'ar': 'أدخن الشيشة', 'en': 'Shisha'},
  's_quit': {'ar': 'أقلعت عن التدخين', 'en': 'I quit'},
  'q_priorities': {
    'ar': 'ما الذي تريد أن تبدأ به؟',
    'en': 'What would you like to work on first?',
  },
  'priorities_hint': {'ar': 'اختر حتى 3', 'en': 'Choose up to 3'},
  'p_sugar': {
    'ar': 'سكر ومشروبات محلّاة أقل',
    'en': 'Less sugar and sweet drinks',
  },
  'p_salt': {'ar': 'تقليل الملح', 'en': 'Eating less salt'},
  'p_food': {'ar': 'أكل صحي أكثر', 'en': 'Eating healthier'},
  'p_activity': {'ar': 'الحركة والرياضة', 'en': 'Moving more'},
  'p_weight': {'ar': 'إنقاص الوزن', 'en': 'Losing weight'},
  'p_medicines': {'ar': 'تذكّر الأدوية', 'en': 'Remembering medicines'},
  'p_smoking': {'ar': 'ترك التدخين', 'en': 'Quitting smoking'},
  // Plan summary
  'plan_ready': {'ar': 'خطتك جاهزة!', 'en': 'Your plan is ready!'},
  'your_plan': {'ar': 'نمط حياتك الصحي', 'en': 'Your healthy lifestyle'},
  'based_on_history': {
    'ar': 'بنيناه على تاريخك الصحي',
    'en': 'Built from your health history',
  },
  'daily_goals': {'ar': 'أهداف يومية', 'en': 'Daily goals'},
  'weekly_goals': {'ar': 'أهداف أسبوعية', 'en': 'Weekly goals'},
  'monthly_goals': {'ar': 'أهداف شهرية', 'en': 'Monthly goals'},
  'plan_changes_note': {
    'ar':
        'خطتك تتغير معك: نرفع الهدف عندما تنجح فيه، ونسهّله عندما يكون صعبًا.',
    'en':
        "Your plan changes with you: we step a goal up when you succeed, and make it easier when it's hard.",
  },
  'start_plan': {'ar': 'ابدأ خطتي اليوم', 'en': 'Start my plan today'},
  'view_plan': {'ar': 'خطتي', 'en': 'My plan'},
  'week_n': {'ar': 'الأسبوع {n} من خطتك', 'en': 'Week {n} of your plan'},
  // Asking the user ("Now" card)
  'morning': {'ar': 'الصباح', 'en': 'Morning'},
  'afternoon': {'ar': 'الظهر', 'en': 'Afternoon'},
  'evening': {'ar': 'المساء', 'en': 'Evening'},
  'anytime': {'ar': 'أي وقت', 'en': 'Anytime'},
  'now_ask': {
    'ar': 'حان الوقت! هل فعلت هذا؟',
    'en': "It's time! Have you done this?",
  },
  'yes_done': {'ar': 'نعم، فعلته', 'en': 'Yes, done'},
  'later': {'ar': 'لاحقًا', 'en': 'Later'},
  'level_n': {'ar': 'المستوى {n}', 'en': 'Level {n}'},
  // Level up
  'ready_title': {
    'ar': 'أحسنت! أنت تبدع',
    'en': "Great job! You're doing so well",
  },
  'ready_q': {
    'ar': 'أنجزت «{goal}» في {days} من آخر 7 أيام. هل أنت جاهز للخطوة التالية؟',
    'en':
        'You did "{goal}" on {days} of the last 7 days. Ready for the next step?',
  },
  'r_level_up': {'ar': 'نعم، الخطوة التالية', 'en': 'Yes, next step'},
  'not_yet': {'ar': 'ليس الآن', 'en': 'Not yet'},
  'stepped_up': {'ar': 'رفعنا هدفك', 'en': 'Goal stepped up'},
  'made_easier': {'ar': 'سهّلنا هدفك', 'en': 'Goal made easier'},
  'plan_changes': {'ar': 'كيف تغيّرت خطتك', 'en': 'How your plan changed'},
  // Water
  'water_count': {
    'ar': 'شربت {n} من {target} أكواب',
    'en': '{n} of {target} cups today',
  },
  'now': {'ar': 'الآن', 'en': 'Now'},
  'why_ask': {'ar': 'لماذا نسأل هذا؟', 'en': 'Why do we ask this?'},
  'part_n': {
    'ar': 'الجزء {n} من {total}: {name}',
    'en': 'Part {n} of {total}: {name}',
  },
  'tab_ask': {'ar': 'اسأل', 'en': 'Ask'},
  'ask_title': {
    'ar': 'اسألني عن ضغطك ونمط حياتك',
    'en': 'Ask me about your blood pressure and lifestyle',
  },
  'ask_sub': {
    'ar':
        'أجيب من الإرشادات الطبية فقط وأذكر المصدر. لا أعطي نصائح عن جرعات الأدوية.',
    'en':
        'I answer only from the medical guidelines and show the source. I never give medicine-dose advice.',
  },
  'ask_try': {'ar': 'جرّب أن تسأل:', 'en': 'Try asking:'},
  'ask_s1': {'ar': 'هل أستطيع أكل الكبسة؟', 'en': 'Can I eat kabsa?'},
  'ask_s2': {
    'ar': 'لماذا الملح مضر لضغطي؟',
    'en': 'Why is salt bad for my blood pressure?',
  },
  'ask_s3': {
    'ar': 'أي تمارين تناسبني مع ألم الركبة؟',
    'en': 'Which exercises suit me with knee pain?',
  },
  'ask_s4': {
    'ar': 'كيف أقيس ضغطي بشكل صحيح؟',
    'en': 'How do I measure my blood pressure correctly?',
  },
  'ask_hint': {'ar': 'اكتب سؤالك هنا…', 'en': 'Type your question…'},
  'ask_send': {'ar': 'إرسال', 'en': 'Send'},
  'ask_doctor_note': {
    'ar': 'اسأل طبيبك أيضًا عن هذا.',
    'en': 'Please also ask your doctor about this.',
  },
  'ai_on': {
    'ar': 'مدعوم بالذكاء الاصطناعي Claude',
    'en': 'Powered by Claude AI',
  },
  'cat_selfcare': {'ar': 'العناية والسلامة', 'en': 'Self-care'},
  'tab_readings': {'ar': 'قراءاتي', 'en': 'Readings'},
  'tab_food': {'ar': 'أكلي', 'en': 'Food'},
  'bp_short': {'ar': 'الضغط', 'en': 'Pressure'},
  'sugar_short': {'ar': 'السكر', 'en': 'Sugar'},
  'log_sugar': {'ar': 'قراءة سكر جديدة', 'en': 'New sugar reading'},
  'sugar_value': {'ar': 'السكر (ملغ/دل)', 'en': 'Sugar (mg/dL)'},
  'mgdl': {'ar': 'ملغ/دل', 'en': 'mg/dL'},
  'ctx_fasting': {'ar': 'صائم', 'en': 'Fasting'},
  'ctx_before_meal': {'ar': 'قبل الأكل', 'en': 'Before a meal'},
  'ctx_after_meal': {'ar': 'بعد الأكل بساعتين', 'en': '2 h after a meal'},
  'ctx_bedtime': {'ar': 'قبل النوم', 'en': 'Bedtime'},
  'when_measured': {'ar': 'متى قست؟', 'en': 'When did you measure?'},
  'glu_low': {'ar': 'منخفض', 'en': 'Low'},
  'glu_in_range': {'ar': 'ضمن الهدف', 'en': 'In target'},
  'glu_high': {'ar': 'أعلى من الهدف', 'en': 'Above target'},
  'glu_goal_note': {
    'ar':
        'الأهداف الشائعة: صائم 80–130، وبعد الأكل أقل من 180 (هدفك قد يختلف).',
    'en':
        'Common goals: fasting 80–130, after meals under 180 (your goal may differ).',
  },
  'sev_symptoms': {
    'ar': 'هل الشخص مشوش أو لا يستطيع البلع أو فقد الوعي؟',
    'en': 'Is the person confused, unable to swallow, or fainted?',
  },
  'food_title': {'ar': 'ماذا آكل اليوم؟', 'en': 'What to eat today'},
  'food_sub': {
    'ar': 'أفكار وجبات تناسب حالتك من الإرشادات',
    'en': 'Meal ideas that fit your condition, from the guidelines',
  },
  'breakfast': {'ar': 'الفطور', 'en': 'Breakfast'},
  'lunch': {'ar': 'الغداء', 'en': 'Lunch'},
  'dinner': {'ar': 'العشاء', 'en': 'Dinner'},
  'snack': {'ar': 'وجبة خفيفة', 'en': 'Snack'},
  'another_idea': {'ar': 'فكرة أخرى', 'en': 'Another idea'},
  'drinks': {'ar': 'المشروبات', 'en': 'Drinks'},
  'limit_these': {'ar': 'قلّل من هذه', 'en': 'Limit these'},
  'tips': {'ar': 'نصائح لك', 'en': 'Tips for you'},
  'why_good': {'ar': 'لماذا هي مناسبة؟', 'en': 'Why it fits you'},
  'water_title': {'ar': 'شرب الماء', 'en': 'Water'},
  'cups_of': {'ar': 'من {target} أكواب', 'en': 'of {target} cups'},
  'add_cup': {'ar': 'شربت كوبًا', 'en': 'I drank a cup'},
  'water_done': {
    'ar': 'ممتاز! وصلت لهدف الماء اليوم',
    'en': "Excellent! You reached today's water goal",
  },
  'water_caution': {
    'ar':
        'مع أمراض القلب أو الكلى قد تحتاج كمية محددة من السوائل. اسأل طبيبك عن الكمية المناسبة لك.',
    'en':
        'With heart or kidney disease you may need a set amount of fluid. Ask your doctor what is right for you.',
  },
  'water_target': {'ar': 'هدف الأكواب اليومي', 'en': 'Daily cups goal'},
  'settings': {'ar': 'الإعدادات', 'en': 'Settings'},
  'switch_lang': {'ar': 'English', 'en': 'العربية'},
  'restart': {'ar': 'ابدأ من جديد', 'en': 'Start over'},
  'reset_demo': {'ar': 'إعادة بيانات العرض', 'en': 'Reset demo data'},
};

class S {
  S(this.lang);
  final String lang;

  static S of(BuildContext context) => S(AppScope.of(context).lang);

  bool get isAr => lang == 'ar';

  String t(String key, [Map<String, Object>? params]) {
    var s = _strings[key]?[lang] ?? _strings[key]?['en'] ?? key;
    params?.forEach((k, v) => s = s.replaceAll('{$k}', '$v'));
    return s;
  }

  /// Pick the language variant of a bilingual API field, e.g. pick(goal, 'title').
  String pick(Map<String, dynamic> obj, String field) =>
      (obj['${field}_$lang'] as String?)?.trim().isNotEmpty == true
      ? obj['${field}_$lang'] as String
      : (obj['${field}_en'] as String? ?? '');
}
