"""Intake questionnaire for hypertension and/or diabetes: the single source of truth for what the app asks.

Sources: ONLY the two reference documents —
  * ACC/AHA 2017: Whelton PK et al., 2017 High Blood Pressure Guideline, J Am Coll Cardiol 2018;71:e127–e248
  * ADA 2026:     American Diabetes Association, Standards of Care in Diabetes—2026, Diabetes Care 2026;49(Suppl. 1)
Each question records its `source`, a plain-language `why`, and the decision it `drives` (rules R1–R22 in
app/diseases/rules.py). Questions about blood pressure appear only for hypertension, diabetes questions
only for diabetes (`show_if`). The app renders this list (GET /api/intake); docs/INTAKE_QUESTIONS.md is
generated from it. Wording is our own, written for older Arabic-speaking adults.
"""
from typing import Any, Dict, List

HTN = {"field": "disease", "in": ["hypertension", "both"]}
DM = {"field": "disease", "in": ["diabetes", "both"]}

FREQ = [
    {"value": "always", "en": "Always", "ar": "دائمًا"},
    {"value": "often", "en": "Often", "ar": "غالبًا"},
    {"value": "sometimes", "en": "Sometimes", "ar": "أحيانًا"},
    {"value": "rarely", "en": "Rarely", "ar": "نادرًا"},
    {"value": "never", "en": "Never", "ar": "أبدًا"},
]

SECTIONS = {
    "about": {"en": "About you", "ar": "عنك"},
    "bp": {"en": "Your blood pressure", "ar": "ضغط دمك"},
    "dm": {"en": "Your diabetes", "ar": "السكري لديك"},
    "health": {"en": "Your health and safety", "ar": "صحتك وسلامتك"},
    "activity": {"en": "Moving", "ar": "الحركة"},
    "food": {"en": "Food and drinks", "ar": "الأكل والمشروبات"},
    "habits": {"en": "Smoking, sleep and mood", "ar": "التدخين والنوم والمزاج"},
    "goals": {"en": "Your goals", "ar": "أهدافك"},
}


def _q(**kw: Any) -> Dict[str, Any]:
    return kw


QUESTIONS: List[Dict[str, Any]] = [
    # ------------------------------------------------------------------ about
    _q(id="condition", section="about", type="choice", field="disease",
       en="Which condition do you have?", ar="ما الحالة التي لديك؟",
       options=[
           {"value": "hypertension", "en": "High blood pressure", "ar": "ارتفاع ضغط الدم", "img": "heart"},
           {"value": "diabetes", "en": "Diabetes", "ar": "السكري", "img": "blood"},
           {"value": "both", "en": "Both", "ar": "الاثنان معًا", "img": "stethoscope"},
       ],
       why_en="Your plan uses the blood pressure guideline, the diabetes guideline, or both.",
       why_ar="خطتك تعتمد على إرشادات الضغط أو إرشادات السكري أو كليهما.",
       source="ACC/AHA 2017 (hypertension); ADA Standards of Care 2026 (diabetes); ACC/AHA §9.6 (hypertension with diabetes).",
       drives="Chooses which guideline rules and knowledge are used (R1–R22)."),
    _q(id="name", section="about", type="text", field="name", optional=True,
       en="What should we call you?", ar="بماذا نناديك؟",
       why_en="So the app can greet you by name. You can skip this.", why_ar="حتى يناديك التطبيق باسمك. يمكنك تخطي هذا السؤال.",
       source="Not clinical (personalisation only).", drives="Greeting only."),
    _q(id="age", section="about", type="number", field="age", unit_en="years", unit_ar="سنة", min=18, max=110, default=60,
       en="How old are you?", ar="كم عمرك؟",
       why_en="Older adults get balance practice, gentler starting goals and enough-protein advice.",
       why_ar="كبار السن يحصلون على تمارين توازن وأهداف بداية أسهل ونصيحة بروتين كافٍ.",
       source="ADA 2026 Section 13 (older adults ≥ 65: recs 13.2, 13.11a–b) and rec 5.38 (balance training).",
       drives="Age ≥ 65 → balance/flexibility and protein goals; smaller start (R14)."),
    _q(id="sex", section="about", type="choice", field="sex",
       en="Are you a man or a woman?", ar="هل أنت رجل أم امرأة؟",
       options=[{"value": "male", "en": "Man", "ar": "رجل", "img": "man"},
                {"value": "female", "en": "Woman", "ar": "امرأة", "img": "woman"}],
       why_en="Some advice is different for women (for example in pregnancy).", why_ar="بعض النصائح تختلف للنساء (مثل الحمل).",
       source="ACC/AHA 2017 §10.2.2 (pregnancy); ADA 2026 rec 10.12.", drives="Shows the pregnancy question (R10)."),
    _q(id="pregnant", section="about", type="choice", field="pregnant",
       show_if={"all": [{"field": "sex", "eq": "female"}, {"field": "age", "lt": 55}]},
       en="Are you pregnant, or planning a pregnancy?", ar="هل أنتِ حامل أو تخططين للحمل؟",
       options=[{"value": "yes", "en": "Yes", "ar": "نعم", "img": "woman"},
                {"value": "no", "en": "No", "ar": "لا", "img": "check"},
                {"value": "not_sure", "en": "Not sure", "ar": "لست متأكدة", "img": "thinking"}],
       why_en="Pregnancy needs a different plan made with your doctor.", why_ar="الحمل يحتاج خطة مختلفة يضعها طبيبك.",
       source="ACC/AHA 2017 §10.2.2 (ACE inhibitors/ARBs must not be used in pregnancy; switch medicines); ADA 2026 rec 10.12.",
       drives="Yes → no lifestyle plan; she is referred to her doctor (R10)."),
    _q(id="body", section="about", type="numbers",
       fields=[{"field": "weight_kg", "en": "Weight", "ar": "الوزن", "unit_en": "kg", "unit_ar": "كجم", "min": 30, "max": 250, "default": 80},
               {"field": "height_cm", "en": "Height", "ar": "الطول", "unit_en": "cm", "unit_ar": "سم", "min": 120, "max": 220, "default": 165}],
       en="Your weight and height", ar="وزنك وطولك",
       why_en="To see if a weight goal would help your blood pressure or blood sugar.",
       why_ar="لمعرفة إن كان هدف الوزن سيفيد ضغطك أو سكرك.",
       source="ACC/AHA 2017 §6.2 rec 1 and Table 15 (weight loss, ~1 mmHg per kg); ADA 2026 rec 5.12 (5–7% weight loss).",
       drives="BMI ≥ 25 → weight goal: ≥ 1 kg (hypertension) or 5–7% (diabetes) (R1)."),
    # ------------------------------------------------------------------ blood pressure
    _q(id="usual_bp", section="bp", type="bp", show_if=HTN,
       fields=[{"field": "usual_systolic", "en": "Top number", "ar": "الرقم الأعلى", "min": 80, "max": 260, "default": 140},
               {"field": "usual_diastolic", "en": "Bottom number", "ar": "الرقم الأسفل", "min": 40, "max": 180, "default": 90}],
       en="What is your blood pressure usually?", ar="كم يكون ضغطك عادةً؟",
       help_en="Roughly, from your home monitor or last clinic visit.", help_ar="تقريبًا، من جهاز البيت أو آخر زيارة.",
       why_en="Very high readings need a doctor first; readings above the goal mean daily home checks.",
       why_ar="القراءات المرتفعة جدًا تحتاج الطبيب أولًا؛ والقراءات فوق الهدف تعني قياسًا يوميًا.",
       source="ACC/AHA 2017 Table 6 (BP categories), §11.2 (crisis > 180/120), §9.6 and ADA 2026 rec 10.4 (goal < 130/80 with diabetes); ADA 2026 S104 (inadequately managed hypertension before exercise).",
       drives="≥ 180/120 → emergency alert (R5); ≥ 160/100 → light activity only + ask doctor (R4); ≥ 130/80 → daily home readings (R6)."),
    _q(id="home_monitor", section="bp", type="choice", field="home_monitor", show_if=HTN,
       en="Do you have a blood pressure monitor at home?", ar="هل لديك جهاز ضغط في البيت؟",
       options=[{"value": "upper_arm", "en": "Yes, with an arm cuff", "ar": "نعم، بكُم على الذراع", "img": "stethoscope"},
                {"value": "wrist", "en": "Yes, on the wrist", "ar": "نعم، على المعصم", "img": "stethoscope"},
                {"value": "none", "en": "No", "ar": "لا", "img": "stop"}],
       why_en="Home readings help your doctor; the guideline recommends a validated automatic arm device.",
       why_ar="قراءات البيت تساعد طبيبك؛ والإرشادات توصي بجهاز ذراع آلي معتمد.",
       source="ACC/AHA 2017 §4.2 and Table 10 (HBPM with automated validated devices); ADA 2026 rec 10.2.",
       drives="Arm cuff → daily home reading goal; wrist/none → ask about a validated arm monitor (R6)."),
    _q(id="medications", section="bp", type="multi", field="medications", allow_other=True, show_if=HTN,
       en="Which blood pressure medicines do you take?", ar="ما أدوية الضغط التي تأخذها؟",
       help_en="Choose all that apply, or none.", help_ar="اختر كل ما ينطبق، أو لا شيء.",
       none_option={"en": "I don't take any", "ar": "لا آخذ أي دواء"},
       options=[{"value": v, "en": v, "ar": v, "img": "pill"} for v in
                ["Amlodipine", "Losartan", "Valsartan", "Lisinopril", "Perindopril", "Hydrochlorothiazide", "Indapamide", "Bisoprolol"]],
       why_en="Some medicines change which foods are safe, and we help you remember them.",
       why_ar="بعض الأدوية تغيّر الأطعمة الآمنة، ونساعدك على تذكّرها.",
       source="ACC/AHA 2017 §6.2 rec 4 and Table 15 (potassium: caution with drugs that reduce potassium excretion); §12.1 (adherence).",
       drives="ACE inhibitor/ARB → no potassium goal (R8); any BP medicine → medicine routine and refill goals (R7)."),
    _q(id="missed_doses", section="bp", type="choice", field="missed_doses",
       show_if={"all": [HTN, {"field": "medications", "not_empty": True}]},
       en="In the last 7 days, did you miss any BP medicine?", ar="في آخر 7 أيام، هل نسيت أي جرعة من دواء الضغط؟",
       options=[{"value": "none", "en": "No, I took them all", "ar": "لا، أخذتها كلها", "img": "check"},
                {"value": "some", "en": "Yes, 1 or 2 times", "ar": "نعم، مرة أو مرتين", "img": "bell"},
                {"value": "many", "en": "Yes, 3 times or more", "ar": "نعم، 3 مرات أو أكثر", "img": "bell"},
                {"value": "stopped", "en": "I stopped taking them", "ar": "توقفت عن أخذها", "img": "stop"}],
       why_en="Missed doses are a main reason blood pressure stays high. We help; we never change doses.",
       why_ar="نسيان الجرعات سبب رئيسي لبقاء الضغط مرتفعًا. نساعدك؛ ولا نغيّر الجرعات أبدًا.",
       source="ACC/AHA 2017 §12.1 (non-adherence is a major cause of poor BP control) and §12.1.1.",
       drives="Missed → medicine routine is the first daily goal; stopped → see your doctor, no medicine goals (R7)."),
    # ------------------------------------------------------------------ diabetes
    _q(id="diabetes_type", section="dm", type="choice", field="diabetes_type", show_if=DM,
       en="What type of diabetes do you have?", ar="ما نوع السكري لديك؟",
       options=[{"value": "type2", "en": "Type 2", "ar": "النوع الثاني", "img": "blood"},
                {"value": "type1", "en": "Type 1", "ar": "النوع الأول", "img": "syringe"},
                {"value": "unknown", "en": "I'm not sure", "ar": "لست متأكدًا", "img": "thinking"}],
       why_en="Activity and food advice differ a little between types.", why_ar="نصائح النشاط والأكل تختلف قليلًا بين النوعين.",
       source="ADA 2026 Section 2 (classification) and rec 5.36 (activity grades differ for type 1 and type 2).",
       drives="Recorded for the doctor report and for the AI's wording (no separate rule)."),
    _q(id="diabetes_meds", section="dm", type="multi", field="diabetes_meds", show_if=DM,
       en="Which diabetes medicines do you use?", ar="ما أدوية السكري التي تستخدمها؟",
       help_en="Choose all that apply.", help_ar="اختر كل ما ينطبق.",
       none_option={"en": "None", "ar": "لا شيء"},
       options=[{"value": "insulin", "en": "Insulin injections", "ar": "إبر الأنسولين", "img": "syringe"},
                {"value": "sulfonylurea", "en": "Gliclazide / glimepiride (sulfonylurea)", "ar": "جليكلازيد / جليمبرايد", "img": "pill"},
                {"value": "metformin", "en": "Metformin", "ar": "ميتفورمين", "img": "pill"},
                {"value": "glp1", "en": "Weekly injection (e.g. semaglutide)", "ar": "إبرة أسبوعية (مثل سيماجلوتايد)", "img": "syringe"},
                {"value": "sglt2", "en": "Empagliflozin / dapagliflozin", "ar": "إمباغليفلوزين / داباغليفلوزين", "img": "pill"},
                {"value": "other", "en": "Other", "ar": "أخرى", "img": "pill"}],
       why_en="Insulin and some tablets can cause low blood sugar, especially with exercise or fasting.",
       why_ar="الأنسولين وبعض الحبوب قد تسبب انخفاض السكر، خاصة مع الرياضة أو الصيام.",
       source="ADA 2026 Section 5 (exercise & hypoglycemia with insulin or insulin secretagogues, S105), recs 6.6, 13.4, 5.28.",
       drives="Insulin or sulfonylurea → low-sugar safety goals (carry glucose, check around exercise) (R15)."),
    _q(id="low_sugar", section="dm", type="choice", field="low_sugar", show_if=DM,
       en="In the last 3 months, did you have low blood sugar (shaky, sweaty, under 70)?",
       ar="في آخر 3 أشهر، هل حدث لك انخفاض في السكر (رجفة، تعرق، أقل من 70)؟",
       options=[{"value": "none", "en": "No", "ar": "لا", "img": "check"},
                {"value": "sometimes", "en": "Once or twice", "ar": "مرة أو مرتين", "img": "bell"},
                {"value": "often", "en": "Often", "ar": "كثيرًا", "img": "bell"},
                {"value": "severe", "en": "Yes, I needed help from someone", "ar": "نعم، واحتجت مساعدة شخص آخر", "img": "ambulance"}],
       why_en="Low sugar is dangerous; your doctor should know and your plan adds safety steps.",
       why_ar="انخفاض السكر خطير؛ يجب أن يعرف طبيبك وتضيف خطتك خطوات أمان.",
       source="ADA 2026 rec 6.10 (review hypoglycemia history at every encounter), Table 6.4 (levels: < 70, < 54, severe), rec 6.15.",
       drives="Any → low-sugar safety goals (R15); needed help → 'tell your doctor' alert."),
    _q(id="glucose_monitor", section="dm", type="choice", field="glucose_monitor", show_if=DM,
       en="How do you check your blood sugar?", ar="كيف تقيس السكر؟",
       options=[{"value": "meter", "en": "Finger-prick meter", "ar": "جهاز وخز الإصبع", "img": "blood"},
                {"value": "cgm", "en": "Sensor on my arm (CGM)", "ar": "حساس على الذراع", "img": "stethoscope"},
                {"value": "none", "en": "I don't check at home", "ar": "لا أقيس في البيت", "img": "stop"}],
       why_en="So your daily goals match how you check.", why_ar="حتى تناسب أهدافك اليومية طريقة قياسك.",
       source="ADA 2026 recs 6.1–6.2 (assessing glycemic status) and Section 7 (blood glucose monitoring, CGM); rec 6.14.",
       drives="Meter/CGM → daily glucose log goal (R19); none → A1C goal only."),
    _q(id="complications", section="dm", type="multi", field="complications", show_if=DM,
       en="Has your doctor told you about any of these?", ar="هل أخبرك طبيبك بأي مما يلي؟",
       none_option={"en": "None of these", "ar": "لا شيء منها"},
       options=[{"value": "retinopathy", "en": "Diabetes affecting my eyes", "ar": "تأثر العين بالسكري", "img": "thinking"},
                {"value": "neuropathy", "en": "Numb, tingling or burning feet", "ar": "تنميل أو حرقان في القدمين", "img": "leg"},
                {"value": "foot_ulcer", "en": "A foot wound or ulcer (now or before)", "ar": "جرح أو قرحة في القدم (الآن أو سابقًا)", "img": "leg"}],
       why_en="Eye or foot problems change which exercises are safe and add foot care.",
       why_ar="مشاكل العين أو القدم تغيّر التمارين الآمنة وتضيف العناية بالقدم.",
       source="ADA 2026 Section 5 (exercise with retinopathy / peripheral neuropathy, S104–S107); recs 12.26, 12.30, 12.31.",
       drives="Eye disease → no vigorous/heavy exercise; numb feet/ulcer → daily foot check, proper shoes, low-impact activity (R18)."),
    _q(id="fasting", section="dm", type="choice", field="fasting", show_if=DM,
       en="Do you plan to fast in Ramadan?", ar="هل تنوي صيام رمضان؟",
       options=[{"value": "yes", "en": "Yes", "ar": "نعم", "img": "moon"},
                {"value": "unsure", "en": "Not sure", "ar": "لست متأكدًا", "img": "thinking"},
                {"value": "no", "en": "No", "ar": "لا", "img": "check"}],
       why_en="Fasting with diabetes needs planning with your doctor well before Ramadan.",
       why_ar="الصيام مع السكري يحتاج تخطيطًا مع طبيبك قبل رمضان بوقت كافٍ.",
       source="ADA 2026 recs 5.32 (IDF-DAR pre-fasting risk assessment) and 5.33 (adjust treatment well in advance).",
       drives="Yes/not sure → 'plan fasting with your care team' goal (R20)."),
    # ------------------------------------------------------------------ health & safety
    _q(id="conditions", section="health", type="multi", field="conditions",
       en="Do you have any of these conditions?", ar="هل لديك أي من هذه الأمراض؟",
       none_option={"en": "None of these", "ar": "لا شيء منها"},
       options=[{"value": "kidney_disease", "en": "Kidney disease", "ar": "مرض في الكلى", "img": "droplet"},
                {"value": "heart_disease", "en": "Heart disease or heart failure", "ar": "مرض في القلب أو ضعف القلب", "img": "heart"},
                {"value": "stroke", "en": "Previous stroke", "ar": "جلطة دماغية سابقة", "img": "brain"},
                {"value": "high_cholesterol", "en": "High cholesterol", "ar": "ارتفاع الكوليسترول", "img": "butter"}],
       why_en="Some conditions change which foods and exercises are safe for you.",
       why_ar="بعض الأمراض تغيّر الأطعمة والتمارين الآمنة لك.",
       source="ACC/AHA 2017 §6.2 rec 4 (potassium contraindicated in CKD), Table 5; ADA 2026 S104 (higher-risk people start with low-intensity exercise).",
       drives="Kidney disease → no potassium goal, fluid caution (R8); heart disease/stroke → gentle activity, ask doctor (R9)."),
    _q(id="activity_safety", section="health", type="multi", field="activity_safety",
       en="Do any of these happen to you?", ar="هل يحدث لك أي مما يلي؟",
       help_en="If you have chest pain right now, call 997.", help_ar="إذا كان لديك ألم في الصدر الآن، اتصل على 997.",
       none_option={"en": "None of these", "ar": "لا شيء منها"},
       options=[{"value": "chest_pain", "en": "Chest pain, or I can do less exercise than before", "ar": "ألم في الصدر، أو أصبحت أتحمل جهدًا أقل من قبل", "img": "heart"},
                {"value": "dizziness", "en": "Dizziness when I stand up, or fainting", "ar": "دوخة عند الوقوف أو إغماء", "img": "thinking"},
                {"value": "supervised_only", "en": "My doctor said to exercise only with supervision", "ar": "قال طبيبي ألا أمارس الرياضة إلا تحت إشراف", "img": "doctor"}],
       why_en="This checks if it is safe to become more active before we suggest exercise.",
       why_ar="هذا يتحقق إن كان آمنًا أن تزيد نشاطك قبل أن نقترح التمارين.",
       source="ADA 2026 Section 5 'Pre-exercise Risk' (S104): reduced exercise tolerance, orthostatic hypotension and other conditions need assessment first; ACC/AHA 2017 §11.2 (chest pain as a warning sign).",
       drives="Any yes → light movement only + 'check with your doctor before more exercise' (R4)."),
    _q(id="mobility", section="health", type="multi", field="limitations",
       en="Do any of these apply to you?", ar="هل ينطبق عليك أي مما يلي؟",
       none_option={"en": "None of these", "ar": "لا شيء منها"},
       options=[{"value": "fallen", "en": "I fell in the past year", "ar": "سقطت خلال السنة الماضية", "img": "bone"},
                {"value": "unsteady", "en": "I feel unsteady when I walk", "ar": "أشعر بعدم الثبات عند المشي", "img": "thinking"},
                {"value": "uses_cane", "en": "I use a cane or walker", "ar": "أستخدم عصا أو مشّاية", "img": "walking"},
                {"value": "knee_pain", "en": "Knee, hip or back pain when I move", "ar": "ألم في الركبة أو الورك أو الظهر عند الحركة", "img": "leg"}],
       why_en="So your exercises are safe for your joints and balance.", why_ar="حتى تكون تمارينك آمنة لمفاصلك وتوازنك.",
       source="ADA 2026 rec 13.2 (screen older adults for falls and persistent pain), rec 5.38 (balance training), S104 (balance impairment).",
       drives="Falls/balance/joint pain → seated or chair-supported activity with balance practice (R14)."),
    # ------------------------------------------------------------------ activity
    _q(id="activity_days", section="activity", type="choice", field="activity_days",
       en="In a usual week, on how many days do you walk briskly or exercise for at least 10 minutes?",
       ar="في أسبوع عادي، كم يومًا تمشي بنشاط أو تمارس الرياضة 10 دقائق على الأقل؟",
       options=[{"value": 0, "en": "0 days", "ar": "ولا يوم", "img": "couch"},
                {"value": 2, "en": "1–2 days", "ar": "يوم أو يومين", "img": "house"},
                {"value": 4, "en": "3–4 days", "ar": "3 إلى 4 أيام", "img": "walking"},
                {"value": 6, "en": "5 days or more", "ar": "5 أيام أو أكثر", "img": "runner"}],
       why_en="We compare you with the guideline goal to set your first step.", why_ar="نقارنك بهدف الإرشادات لنحدد خطوتك الأولى.",
       source="ADA 2026 rec 5.34 (evaluate baseline physical activity) and 5.36 (≥ 150 min/week over ≥ 3 days); ACC/AHA 2017 Table 15 (aerobic 90–150 min/week).",
       drives="Weekly minutes = days × minutes; below goal → activity goal a little above current level (R4)."),
    _q(id="activity_minutes", section="activity", type="choice", field="activity_minutes",
       show_if={"field": "activity_days", "gt": 0},
       en="On those days, for how long?", ar="في تلك الأيام، لكم من الوقت؟",
       options=[{"value": 10, "en": "About 10 minutes", "ar": "حوالي 10 دقائق", "img": "walking"},
                {"value": 20, "en": "About 20 minutes", "ar": "حوالي 20 دقيقة", "img": "walking"},
                {"value": 30, "en": "30 minutes or more", "ar": "30 دقيقة أو أكثر", "img": "runner"}],
       why_en="Together with the days, this shows how active you are now.", why_ar="مع عدد الأيام، يوضح هذا مستوى نشاطك الآن.",
       source="ADA 2026 rec 5.34 (baseline activity); ACC/AHA 2017 Table 15.", drives="Weekly activity minutes (R4)."),
    _q(id="sitting", section="activity", type="choice", field="sitting_hours", show_if=DM,
       en="On a usual day, how many hours do you spend sitting?", ar="في يوم عادي، كم ساعة تقضيها جالسًا؟",
       options=[{"value": "lt4", "en": "Less than 4 hours", "ar": "أقل من 4 ساعات", "img": "walking"},
                {"value": "4_8", "en": "4 to 8 hours", "ar": "4 إلى 8 ساعات", "img": "chair"},
                {"value": "gt8", "en": "More than 8 hours", "ar": "أكثر من 8 ساعات", "img": "couch"}],
       why_en="Breaking up long sitting helps blood sugar.", why_ar="كسر الجلوس الطويل يساعد على ضبط السكر.",
       source="ADA 2026 rec 5.34 (evaluate sedentary time; interrupt sitting at least every 30 min).",
       drives="Long sitting → 'move every 30 minutes' goal (R22)."),
    # ------------------------------------------------------------------ food
    _q(id="fruit_veg", section="food", type="choice", field="fruit_veg",
       en="On a usual day, how many servings of vegetables and fruit do you eat?",
       ar="في يوم عادي، كم حصة من الخضار والفواكه تأكل؟",
       help_en="1 serving = 1 piece of fruit, or a small bowl of salad or cooked vegetables.",
       help_ar="الحصة = حبة فاكهة، أو صحن صغير من السلطة أو الخضار المطبوخة.",
       options=[{"value": "0", "en": "None", "ar": "ولا حصة", "img": "stop"},
                {"value": "1_2", "en": "1–2", "ar": "1 إلى 2", "img": "salad"},
                {"value": "3_4", "en": "3–4", "ar": "3 إلى 4", "img": "salad"},
                {"value": "5_plus", "en": "5 or more", "ar": "5 أو أكثر", "img": "herb"}],
       why_en="Vegetables and fruit lower blood pressure (DASH) and help blood sugar.",
       why_ar="الخضار والفواكه تخفض الضغط (نظام داش) وتساعد على ضبط السكر.",
       source="ACC/AHA 2017 §6.2 rec 2, Table 15 (DASH: rich in fruits and vegetables); ADA 2026 rec 5.14 (non-starchy vegetables, whole fruits).",
       drives="Few servings → daily vegetables goal (R3)."),
    _q(id="refined_grains", section="food", type="choice", field="refined_grains", options=FREQ,
       en="How often is your bread or rice white (not whole grain)?", ar="كم مرة يكون خبزك أو أرزك أبيض (غير أسمر)؟",
       why_en="Whole grains and fibre raise blood sugar more slowly and are part of DASH.",
       why_ar="الحبوب الكاملة والألياف ترفع السكر ببطء أكثر وهي جزء من نظام داش.",
       source="ADA 2026 recs 5.14, 5.24 (high-fibre, minimally processed carbohydrates); ACC/AHA 2017 Table 15 (DASH: whole grains).",
       drives="Always/often → whole-grain / high-fibre goal (R17)."),
    _q(id="sugary_drinks", section="food", type="choice", field="sugary_drinks", options=FREQ,
       en="How often do you drink juice, soft drinks or sweetened tea/coffee?",
       ar="كم مرة تشرب العصير أو المشروبات الغازية أو الشاي/القهوة المحلّاة؟",
       why_en="Sugary drinks, including juice, raise blood sugar quickly. Water is best.",
       why_ar="المشروبات السكرية، ومنها العصير، ترفع السكر بسرعة. الماء هو الأفضل.",
       source="ADA 2026 recs 5.21 (choose water) and 5.25 (replace sugar-sweetened beverages, including juices).",
       drives="Sometimes or more → 'water instead' goal (R16)."),
    _q(id="salt_table", section="food", type="choice", field="salt_table", options=FREQ,
       en="How often do you add salt to your food at the table?", ar="كم مرة تضيف الملح إلى طعامك على السفرة؟",
       why_en="Less salt is one of the strongest ways to lower blood pressure.", why_ar="تقليل الملح من أقوى الطرق لخفض الضغط.",
       source="ACC/AHA 2017 §6.2 rec 3, Table 15 (sodium < 1500 mg/day or ≥ 1000 mg reduction); ADA 2026 rec 5.20 (< 2300 mg/day).",
       drives="Always/often → 'no salt shaker' goal (R2)."),
    _q(id="salt_cooking", section="food", type="choice", field="salt_cooking", options=FREQ,
       en="How often are salt, stock cubes or seasoning powder added when cooking at home?",
       ar="كم مرة يُضاف الملح أو مكعب المرق أو البهارات المملحة عند الطبخ في البيت؟",
       why_en="Stock cubes and salty seasoning are big hidden sources of salt.", why_ar="مكعبات المرق والبهارات المملحة مصادر كبيرة للملح المخفي.",
       source="ACC/AHA 2017 §6.2 rec 3, Table 15; ADA 2026 rec 5.20 (limit processed foods to lower sodium).",
       drives="Always/often → stock-cube cooking goal (R2)."),
    _q(id="salty_foods", section="food", type="choice", field="salty_foods", options=FREQ,
       en="How often do you eat salty or processed foods (white cheese, pickles, chips, fast food)?",
       ar="كم مرة تأكل أطعمة مالحة أو مصنّعة (جبن أبيض، مخللات، شيبس، وجبات سريعة)؟",
       why_en="Most salt comes from processed and ready-made food.", why_ar="معظم الملح يأتي من الأطعمة المصنّعة والجاهزة.",
       source="ADA 2026 rec 5.20 and 5.14 (minimise processed and ultra-processed foods); ACC/AHA 2017 Table 15.",
       drives="Always/often → salty-food swap goals (R2)."),
    # ------------------------------------------------------------------ habits
    _q(id="tobacco", section="habits", type="choice", field="tobacco",
       en="Do you smoke or vape (cigarettes, shisha, e-cigarettes)?", ar="هل تدخن (سجائر، شيشة، سجائر إلكترونية)؟",
       options=[{"value": "daily", "en": "Yes, every day", "ar": "نعم، كل يوم", "img": "cigarette"},
                {"value": "sometimes", "en": "Yes, sometimes", "ar": "نعم، أحيانًا", "img": "cigarette"},
                {"value": "quit", "en": "I quit", "ar": "أقلعت", "img": "trophy"},
                {"value": "never", "en": "Never", "ar": "لم أدخن أبدًا", "img": "no_smoking"}],
       why_en="Smoking raises the risk of heart disease, stroke and diabetes complications.",
       why_ar="التدخين يزيد خطر أمراض القلب والجلطة ومضاعفات السكري.",
       source="ADA 2026 rec 5.40 (ask routinely about tobacco or vape use; advise complete avoidance); ACC/AHA 2017 Table 5 (smoking as a modifiable CVD risk factor).",
       drives="Current use → smoke-free goal (R11)."),
    _q(id="sleep_hours", section="habits", type="choice", field="sleep_hours",
       en="How many hours do you usually sleep at night?", ar="كم ساعة تنام عادةً في الليل؟",
       options=[{"value": "lt5", "en": "Less than 5", "ar": "أقل من 5", "img": "moon"},
                {"value": "5_6", "en": "5 to 6", "ar": "5 إلى 6", "img": "moon"},
                {"value": "7_9", "en": "7 to 9", "ar": "7 إلى 9", "img": "moon"},
                {"value": "gt9", "en": "More than 9", "ar": "أكثر من 9", "img": "moon"}],
       why_en="Sleep problems are common with diabetes and high blood pressure.", why_ar="مشاكل النوم شائعة مع السكري والضغط.",
       source="ADA 2026 recs 5.56 (screen for sleep health) and 5.57 (sleep-promoting routines).",
       drives="Short sleep (with diabetes) → sleep-routine goal (R12)."),
    _q(id="sleep_signs", section="habits", type="multi", field="sleep_signs",
       en="Do any of these happen to you?", ar="هل يحدث لك أي مما يلي؟",
       none_option={"en": "None of these", "ar": "لا شيء منها"},
       options=[{"value": "snoring", "en": "I snore loudly", "ar": "أشخر بصوت عالٍ", "img": "moon"},
                {"value": "tired", "en": "I often feel sleepy in the day", "ar": "أشعر غالبًا بالنعاس في النهار", "img": "couch"},
                {"value": "observed", "en": "Someone saw me stop breathing in sleep", "ar": "رآني أحد أتوقف عن التنفس أثناء النوم", "img": "thinking"}],
       why_en="These can be signs of sleep apnoea, which is linked to high blood pressure and is treatable.",
       why_ar="قد تكون علامات انقطاع النفس أثناء النوم، المرتبط بارتفاع الضغط والقابل للعلاج.",
       source="ACC/AHA 2017 §5.4.4 and Table 5 (obstructive sleep apnoea); ADA 2026 rec 5.56 (screen for sleep disorders).",
       drives="Possible sleep apnoea → 'ask your doctor' note on plan and doctor report; not a diagnosis (R12)."),
    _q(id="mood", section="habits", type="choice", field="mood", show_if=DM,
       en="In the last 2 weeks, have you felt down or overwhelmed by your diabetes?",
       ar="في آخر أسبوعين، هل شعرت بالإحباط أو الإرهاق بسبب السكري؟",
       options=[{"value": "no", "en": "No", "ar": "لا", "img": "check"},
                {"value": "sometimes", "en": "Sometimes", "ar": "أحيانًا", "img": "thinking"},
                {"value": "often", "en": "Often", "ar": "كثيرًا", "img": "thinking"}],
       why_en="Feelings matter for diabetes care; your care team can help.", why_ar="المشاعر مهمة في رعاية السكري؛ وفريقك الطبي يستطيع المساعدة.",
       source="ADA 2026 recs 5.42–5.48 (psychosocial care; screen for diabetes distress, anxiety, depression). Single question, not a validated screening tool.",
       drives="Sometimes/often → 'tell your care team' note (R21); not a diagnosis."),
    # ------------------------------------------------------------------ goals
    _q(id="priorities", section="goals", type="multi", field="priorities", max=3,
       en="What would you like to work on first?", ar="ما الذي تريد أن تبدأ به؟",
       help_en="Choose up to 3.", help_ar="اختر حتى 3.",
       options=[{"value": "salt", "en": "Eating less salt", "ar": "تقليل الملح", "img": "salt"},
                {"value": "sugar", "en": "Less sugar and sweet drinks", "ar": "سكر ومشروبات محلّاة أقل", "img": "cup"},
                {"value": "food", "en": "Eating healthier", "ar": "أكل صحي أكثر", "img": "salad"},
                {"value": "activity", "en": "Moving more", "ar": "الحركة والرياضة", "img": "walking"},
                {"value": "weight", "en": "Losing weight", "ar": "إنقاص الوزن", "img": "scale"},
                {"value": "medicines", "en": "Remembering medicines", "ar": "تذكّر الأدوية", "img": "pill"},
                {"value": "smoking", "en": "Quitting smoking", "ar": "ترك التدخين", "img": "no_smoking"},
                {"value": "sleep", "en": "Sleeping better", "ar": "نوم أفضل", "img": "moon"}],
       why_en="People keep going longer with changes they chose themselves.", why_ar="يستمر الناس أكثر في التغييرات التي اختاروها بأنفسهم.",
       source="ADA 2026 Section 4 (person-centred collaborative care; shared goal setting) and rec 5.1 (DSMES); ACC/AHA 2017 §12 (team-based, patient-centred care).",
       drives="Chosen areas come first in the plan (R13). Safety rules still apply."),
]


def public_questions() -> List[Dict[str, Any]]:
    return QUESTIONS
